apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eks-bootcamp-web.fullname" . }}
  labels:
    {{- include "eks-bootcamp-web.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/change-cause: "Deployed with Helm - {{ .Values.image.tag }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eks-bootcamp-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eks-bootcamp-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: eks-bootcamp-config
            - secretRef:
                name: eks-bootcamp-secret

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}