name: EKS Bootcamp CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository ophalen
        uses: actions/checkout@v4
        
      - name: Eerste CI-controle
        run: echo "EKS Bootcamp CI pipeline gestart"
        
